#############################################################################
# Makefile for building: CisClientPro
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  CisClientPro.pro
# Template: subdirs
# Command: D:\Qt\Qt5.7.1\5.7\mingw53_32\bin\qmake.exe -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile CisClientPro.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\Qt5.7.1\5.7\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-AlarmClient \
		sub-ThingsSDK


sub-AlarmClient-qmake_all:  FORCE
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	cd AlarmClient\ && $(MAKE) -f Makefile qmake_all
sub-AlarmClient: FORCE
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-AlarmClient-make_first: FORCE
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-AlarmClient-all: FORCE
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-AlarmClient-clean: FORCE
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-AlarmClient-distclean: FORCE
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-AlarmClient-install_subtargets: FORCE
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-AlarmClient-uninstall_subtargets: FORCE
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ThingsSDK-qmake_all:  FORCE
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	cd ThingsSDK\ && $(MAKE) -f Makefile qmake_all
sub-ThingsSDK: FORCE
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-ThingsSDK-make_first: FORCE
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-ThingsSDK-all: FORCE
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-ThingsSDK-clean: FORCE
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-ThingsSDK-distclean: FORCE
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ThingsSDK-install_subtargets: FORCE
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-ThingsSDK-uninstall_subtargets: FORCE
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: CisClientPro.pro D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/win32-g++/qmake.conf D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/spec_pre.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/qdevice.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/device_config.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/common/angle.conf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/qconfig.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/qt_functions.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/qt_config.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/win32/qt_config.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/win32-g++/qmake.conf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/exclusive_builds.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/toolchain.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/default_pre.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/win32/default_pre.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/resolve_config.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/default_post.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/qml_debug.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/win32/rtti.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/precompile_header.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/warn_on.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/file_copies.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/win32/windows.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/testcase_targets.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/exceptions.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/yacc.prf \
		D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/lex.prf \
		CisClientPro.pro
	$(QMAKE) -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile CisClientPro.pro
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/spec_pre.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/qdevice.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/device_config.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/common/angle.conf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/qconfig.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_core.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_help.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_location.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_network.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_script.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/qt_functions.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/qt_config.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/win32/qt_config.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/win32-g++/qmake.conf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/spec_post.prf:
.qmake.stash:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/exclusive_builds.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/toolchain.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/default_pre.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/win32/default_pre.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/resolve_config.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/default_post.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/qml_debug.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/win32/rtti.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/precompile_header.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/warn_on.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/file_copies.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/win32/windows.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/testcase_targets.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/exceptions.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/yacc.prf:
D:/Qt/Qt5.7.1/5.7/mingw53_32/mkspecs/features/lex.prf:
CisClientPro.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile CisClientPro.pro

qmake_all: sub-AlarmClient-qmake_all sub-ThingsSDK-qmake_all FORCE

make_first: sub-AlarmClient-make_first sub-ThingsSDK-make_first  FORCE
all: sub-AlarmClient-all sub-ThingsSDK-all  FORCE
clean: sub-AlarmClient-clean sub-ThingsSDK-clean  FORCE
distclean: sub-AlarmClient-distclean sub-ThingsSDK-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-AlarmClient-install_subtargets sub-ThingsSDK-install_subtargets FORCE
uninstall_subtargets: sub-AlarmClient-uninstall_subtargets sub-ThingsSDK-uninstall_subtargets FORCE

sub-AlarmClient-debug:
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-ThingsSDK-debug:
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-AlarmClient-debug sub-ThingsSDK-debug

sub-AlarmClient-release:
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-ThingsSDK-release:
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-AlarmClient-release sub-ThingsSDK-release

sub-AlarmClient-check:
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-ThingsSDK-check:
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-AlarmClient-check sub-ThingsSDK-check

sub-AlarmClient-benchmark:
	@if not exist AlarmClient\ mkdir AlarmClient\ & if not exist AlarmClient\ exit 1
	cd AlarmClient\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\AlarmClient\AlarmClient.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-ThingsSDK-benchmark:
	@if not exist ThingsSDK\ mkdir ThingsSDK\ & if not exist ThingsSDK\ exit 1
	cd ThingsSDK\ && ( if not exist Makefile $(QMAKE) E:\WorkDir\QT\CisClientPro\ThingsSDK\ThingsSDK.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
benchmark: sub-AlarmClient-benchmark sub-ThingsSDK-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

